#pragma once

#define WIFI_FALLBACK_TIMEOUT_MS 120000UL

#define FIREBASE_HOST "PLACE FOR HOST"
#define FIREBASE_AUTH "PLACE FOR TOKEN"

#define SESSION_SECRET "CHANGE TO LONG RANDOM KEY 32+"

#define EMERGENCY_PIN "999999"
